server:
  port: 8888
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/crm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  springfox:
    documentation:
      enabled: true
  swagger:
    authorization:
      name: ywwy
    base-package: com.neusoft.crm.controller
    base-path: /**
 